### ISSUE TITLE
Normalize login account name field to lowercase

### ISSUE THREAD

**Issue by pfunks** [PBSA/peerplays-core-gui#1]
A user with the account @arranalt-4 reported an issue with Peerplays core not recognizing an account name and gave me their account name with the first letter capitalized. The account exists on the blockchain. It's possible they typed it in that way in the Peerplays core client to log in and received this error.

![image](https://user-images.githubusercontent.com/22420130/27059765-daf11a0c-4f9d-11e7-91e4-16fd3329197f.png)

I notice that if you type a space after entering an account with capital letters, the field will normalize to lowercase, but this functionality is not working when switching fields with mouse or Tab key.

Tested platform: Windows

**Comment by mseaward** [comment]
Resolved on develop branch.
