### ISSUE TITLE
Connecting Error

### ISSUE THREAD

**Issue by JCDez** [PBSA/peerplays-core-gui#10]
The Peerplays core program is loaded but immediately displays the error message "Can't connect to Blockchain" with a "Try Again" button. This happens before you even get to see the login page.

I have attempted uninstalling and reinstalling the client and tried hitting "Try Again" for a full half hour to see if it would randomly, successfully connect without any success.

**Comment by Blakey** [comment]
Exactly the same issue here (Peerplays Core v1.4.13)!

**Comment by TheRock247** [comment]
Same problem here

**Comment by KeeganPBSA** [comment]
Thanks for reporting. PBSA is working on this problem as we speak. Will post with more details when we know more. Thank you for your patients.

**Comment by KeeganPBSA** [comment]
Hello Community! The peerplays wallet experienced an outage earlier today. The outage was resolved at 4:45PM ADT.

**Comment by JCDez** [comment]
Core wallet is still giving me the exact same error message. Just tried again 2 minutes ago.
