### ISSUE TITLE
Unable to "paste" on macbook

### ISSUE THREAD

**Issue by TheTaconator** [PBSA/peerplays-core-gui#17]
Richard Lionheart reports:

> With my macbook, I am unable to use the "paste" function in any of the input fields. The app forces me to manually [type] my username and my password, along with every other input field I cannot "paste" data into.

**Comment by KeeganPBSA** [comment]
Please indicate the version of the wallet, and the operating system you are using (You say you're using mac hardware, are you running an Debian VM?).

**Comment by TheTaconator** [comment]
On behalf of Richard Lionheart:
> Wallet version 0.1.3.
> OS X El Capitan 10.11.6
> Macbook Pro hardware (no VM)
