### ISSUE TITLE
Question: checking balance with public key

### ISSUE THREAD

**Issue by jcalfee** [PBSA/peerplays-core-gui#19]
Before I provide my owner private key, is there a way to check my balance using my owner public key?

![screenshot from 2018-07-05 19-18-38](https://user-images.githubusercontent.com/204121/42353777-490b860a-8088-11e8-9d41-1afa7f7ea9b8.png)

**Comment by phiguy** [comment]
If you know what your account name is on peerplays, then you can check your balance on peerplaysdb.com
