### ISSUE TITLE
How to connect to the Peerplays testnet?

### ISSUE THREAD

**Issue by lonnieOST** [PBSA/peerplays-core-gui#22]
Hello,

I want to test out the peerplays gui wallet and connect to the Peerplays TESTNET.

How can this be done?

Thanks

**Comment by phiguy** [comment]
You can navigate to the settings page and input a custom endpoint. You will need to ask one of the testnet witnesses for an endpoint. You can use mine if you like. 

ws://35.159.10.69:8090

Or you can see a full list of details [here](https://peerplays.atlassian.net/wiki/spaces/PD/pages/15564866/Witness+Node+Connection+Details).
